#!/bin/sh

echo export PS1=\"[\\u@\\h \\w]\\\\$ \" >> /etc/bashrc
echo set completion-ignore-case on >> /etc/inputrc
echo set show-all-if-ambiguous on >> /etc/inputrc
echo HISTSIZE=10000000 >> /etc/profile
echo HISEFILESIZE=10000000 >> /etc/profile
echo kernel.sysrq=1 >> /etc/sysctl.conf
sysctl --system
exit
