#!/bin/bash

GATEWAY=$(ip -4 route list 0/0 | cut -d\  -f3)
[[ -z "$GATEWAY" ]] && echo does not exist default route && exit 1
[[ $(echo $GATEWAY) =~ " " ]] && echo There are multiple default route && exit 2

proxy_ip=$1
[[ -z "$proxy_ip" ]] && echo no proxy server ip && exit 3

socks_port=$2
[[ -z "$socks_port" ]] && echo no socks port && exit 4

ip route flush default
ip tuntap add dev tun0 mode tun
ip addr add 10.0.0.2/24 dev tun0
ip link set tun0 up
ip route add $proxy_ip via $GATEWAY metric 5
ip route add default via 10.0.0.1 dev tun0 metric 6

dir=/tmp/global_socks_proxy
mkdir $dir

cat > $dir/config <<EOF
resolv_conf = $dir/proxy-resolv.conf
socks_port = $socks_port
EOF

cat > $dir/proxy-resolv.conf <<EOF
8.8.8.8
8.8.4.4
EOF
cp /etc/resolv.conf $dir/resolv.conf

dns-socks-proxy $dir/config
badvpn-tun2socks --tundev tun0 --netif-ipaddr 10.0.0.1 --netif-netmask 255.255.255.0 --socks-server-addr 127.0.0.1:$socks_port --loglevel 0
pkill dns-socks-proxy

cp $dir/resolv.conf /etc/resolv.conf
rm -rf $dir

ip link set tun0 down
ip tuntap del dev tun0 mode tun
ip route add default via $GATEWAY
